site_name: ow11is
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode